"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AdditionalPurchaseData = void 0;
/**
* The additional information about the purchase. Used for Level 2 and Level 3 Processing.
*/
class AdditionalPurchaseData {
    /**
    * The customer reference for the purchase (max 17 characters).
    */
    'customerReferenceNumber';
    /**
    * The duty in cents on the total purchase amount for the order
    */
    'customsDutyAmount';
    /**
    * The ISO country code of the order destination.
    */
    'destinationCountryCode';
    /**
    * The postal code of the order destination (10 characters)
    */
    'destinationPostalCode';
    /**
    * The amount in cents of the discount for the order.
    */
    'discountAmount';
    /**
    * The order\'s invoice number (max 15 characters)
    */
    'invoiceReferenceNumber';
    'itemData';
    'orderDate';
    /**
    * Total aggregate tax amount in cents for the entire purchase. Field is automatically calculated if you pass in the itemized tax amounts.   For non-taxable transactions either set `sales_tax` to 0 or omit from payload and also set `tax_exempt` to **True**.
    */
    'salesTax';
    /**
    * The postal code from where order is shipped (10 characters)
    */
    'shipFromPostalCode';
    /**
    * The shipping cost in cents for the order.
    */
    'shippingAmount';
    /**
    * For tax exempt purchases set to True.
    */
    'taxExempt';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "customerReferenceNumber",
            "baseName": "customer_reference_number",
            "type": "string"
        },
        {
            "name": "customsDutyAmount",
            "baseName": "customs_duty_amount",
            "type": "number"
        },
        {
            "name": "destinationCountryCode",
            "baseName": "destination_country_code",
            "type": "string"
        },
        {
            "name": "destinationPostalCode",
            "baseName": "destination_postal_code",
            "type": "string"
        },
        {
            "name": "discountAmount",
            "baseName": "discount_amount",
            "type": "number"
        },
        {
            "name": "invoiceReferenceNumber",
            "baseName": "invoice_reference_number",
            "type": "string"
        },
        {
            "name": "itemData",
            "baseName": "item_data",
            "type": "Array<AdditionalPurchaseDataItemDataInner>"
        },
        {
            "name": "orderDate",
            "baseName": "order_date",
            "type": "AdditionalPurchaseDataOrderDate"
        },
        {
            "name": "salesTax",
            "baseName": "sales_tax",
            "type": "number"
        },
        {
            "name": "shipFromPostalCode",
            "baseName": "ship_from_postal_code",
            "type": "string"
        },
        {
            "name": "shippingAmount",
            "baseName": "shipping_amount",
            "type": "number"
        },
        {
            "name": "taxExempt",
            "baseName": "tax_exempt",
            "type": "boolean"
        }
    ];
    static getAttributeTypeMap() {
        return AdditionalPurchaseData.attributeTypeMap;
    }
}
exports.AdditionalPurchaseData = AdditionalPurchaseData;
