/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateSubscriptionScheduleRequestFixedTimeIntervalOffset } from './createSubscriptionScheduleRequestFixedTimeIntervalOffset';
import { CreateSubscriptionScheduleRequestPeriodOffset } from './createSubscriptionScheduleRequestPeriodOffset';

/**
* 
*/
export class CreateSubscriptionScheduleRequest {
    /**
    * Subscription Schedule type. For subscriptions, the type is **FEE**.
    */
    'lineItemType': CreateSubscriptionScheduleRequest.LineItemTypeEnum;
    /**
    * Human readable name.
    */
    'nickname': string;
    'fixedTimeIntervalOffset'?: CreateSubscriptionScheduleRequestFixedTimeIntervalOffset | null;
    'periodOffset'?: CreateSubscriptionScheduleRequestPeriodOffset | null;
    /**
    * Specify the type of schedule: - **FIXED\\_TIME\\_INTERVAL**: Charges a Merchant on a fixed hourly interval. - **PERIODIC\\_MONTHLY**: Charges a Merchant once a month on a specific day. - **PERIODIC\\_YEARLY**: Charges a Merchant once a year on a specific day and month.
    */
    'subscriptionType': CreateSubscriptionScheduleRequest.SubscriptionTypeEnum;
    /**
    * Key value pair for annotating custom meta data (e.g. order numbers).
    */
    'tags'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lineItemType",
            "baseName": "line_item_type",
            "type": "CreateSubscriptionScheduleRequest.LineItemTypeEnum"
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string"
        },
        {
            "name": "fixedTimeIntervalOffset",
            "baseName": "fixed_time_interval_offset",
            "type": "CreateSubscriptionScheduleRequestFixedTimeIntervalOffset"
        },
        {
            "name": "periodOffset",
            "baseName": "period_offset",
            "type": "CreateSubscriptionScheduleRequestPeriodOffset"
        },
        {
            "name": "subscriptionType",
            "baseName": "subscription_type",
            "type": "CreateSubscriptionScheduleRequest.SubscriptionTypeEnum"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return CreateSubscriptionScheduleRequest.attributeTypeMap;
    }
}

export namespace CreateSubscriptionScheduleRequest {
    export enum LineItemTypeEnum {
        Fee = <any> 'FEE'
    }
    export enum SubscriptionTypeEnum {
        FixedTimeInterval = <any> 'FIXED_TIME_INTERVAL',
        PeriodicMonthly = <any> 'PERIODIC_MONTHLY',
        PeriodicYearly = <any> 'PERIODIC_YEARLY'
    }
}
