/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateWebhookRequestAuthentication } from './createWebhookRequestAuthentication';

export class CreateWebhookRequest {
    'authentication'?: CreateWebhookRequestAuthentication;
    /**
    * Set to false to disable Webhooks. Default value when created is true.
    */
    'enabled'?: boolean;
    /**
    * The HTTP or HTTPS URL where callbacks (i.e. events) will be sent via POST request (max 120 characters).
    */
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authentication",
            "baseName": "authentication",
            "type": "CreateWebhookRequestAuthentication"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateWebhookRequest.attributeTypeMap;
    }
}

