"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateFeeRequest = void 0;
class CreateFeeRequest {
    static getAttributeTypeMap() {
        return CreateFeeRequest.attributeTypeMap;
    }
}
exports.CreateFeeRequest = CreateFeeRequest;
CreateFeeRequest.discriminator = undefined;
CreateFeeRequest.attributeTypeMap = [
    {
        "name": "tags",
        "baseName": "tags",
        "type": "{ [key: string]: string; }"
    },
    {
        "name": "amount",
        "baseName": "amount",
        "type": "number"
    },
    {
        "name": "currency",
        "baseName": "currency",
        "type": "Currency"
    },
    {
        "name": "label",
        "baseName": "label",
        "type": "string"
    },
    {
        "name": "feeSubtype",
        "baseName": "fee_subtype",
        "type": "CreateFeeRequest.FeeSubtypeEnum"
    },
    {
        "name": "feeType",
        "baseName": "fee_type",
        "type": "FeeType"
    },
    {
        "name": "linkedId",
        "baseName": "linked_id",
        "type": "string"
    },
    {
        "name": "linkedType",
        "baseName": "linked_type",
        "type": "CreateFeeRequest.LinkedTypeEnum"
    },
    {
        "name": "merchantId",
        "baseName": "merchant_id",
        "type": "string"
    },
    {
        "name": "settlementDelayDays",
        "baseName": "settlement_delay_days",
        "type": "number"
    }
];
(function (CreateFeeRequest) {
    let FeeSubtypeEnum;
    (function (FeeSubtypeEnum) {
        FeeSubtypeEnum[FeeSubtypeEnum["Custom"] = 'CUSTOM'] = "Custom";
    })(FeeSubtypeEnum = CreateFeeRequest.FeeSubtypeEnum || (CreateFeeRequest.FeeSubtypeEnum = {}));
    let LinkedTypeEnum;
    (function (LinkedTypeEnum) {
        LinkedTypeEnum[LinkedTypeEnum["Application"] = 'APPLICATION'] = "Application";
        LinkedTypeEnum[LinkedTypeEnum["Platform"] = 'PLATFORM'] = "Platform";
        LinkedTypeEnum[LinkedTypeEnum["Subscription"] = 'SUBSCRIPTION'] = "Subscription";
        LinkedTypeEnum[LinkedTypeEnum["Transfer"] = 'TRANSFER'] = "Transfer";
    })(LinkedTypeEnum = CreateFeeRequest.LinkedTypeEnum || (CreateFeeRequest.LinkedTypeEnum = {}));
})(CreateFeeRequest = exports.CreateFeeRequest || (exports.CreateFeeRequest = {}));
//# sourceMappingURL=createFeeRequest.js.map