"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateIdentityRequestEntityDob = void 0;
/**
* The control owner\'s date of birth.
*/
class CreateIdentityRequestEntityDob {
    static getAttributeTypeMap() {
        return CreateIdentityRequestEntityDob.attributeTypeMap;
    }
}
exports.CreateIdentityRequestEntityDob = CreateIdentityRequestEntityDob;
CreateIdentityRequestEntityDob.discriminator = undefined;
CreateIdentityRequestEntityDob.attributeTypeMap = [
    {
        "name": "year",
        "baseName": "year",
        "type": "number"
    },
    {
        "name": "day",
        "baseName": "day",
        "type": "number"
    },
    {
        "name": "month",
        "baseName": "month",
        "type": "number"
    }
];
