"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CreateSubscriptionAmountRequestFeeAmountData = void 0;
/**
* The amount and currency of this `Subsciption Amount`.
*/
class CreateSubscriptionAmountRequestFeeAmountData {
    'currency';
    /**
    * A positive integer in cents representing how much to charge on a recurring basis.
    */
    'amount';
    /**
    * The display name of the `Subscirption Amount` that can be used for filtering purposes.
    */
    'label';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Currency"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        }
    ];
    static getAttributeTypeMap() {
        return CreateSubscriptionAmountRequestFeeAmountData.attributeTypeMap;
    }
}
exports.CreateSubscriptionAmountRequestFeeAmountData = CreateSubscriptionAmountRequestFeeAmountData;
//# sourceMappingURL=createSubscriptionAmountRequestFeeAmountData.js.map