"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DisputesListEmbedded = void 0;
class DisputesListEmbedded {
    /**
    * `Dispute` object.
    */
    'disputes';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "disputes",
            "baseName": "disputes",
            "type": "Set<Dispute>"
        }
    ];
    static getAttributeTypeMap() {
        return DisputesListEmbedded.attributeTypeMap;
    }
}
exports.DisputesListEmbedded = DisputesListEmbedded;
//# sourceMappingURL=disputesListEmbedded.js.map