"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorGeneric = void 0;
class ErrorGeneric {
    static getAttributeTypeMap() {
        return ErrorGeneric.attributeTypeMap;
    }
}
exports.ErrorGeneric = ErrorGeneric;
ErrorGeneric.discriminator = undefined;
ErrorGeneric.attributeTypeMap = [
    {
        "name": "total",
        "baseName": "total",
        "type": "number"
    },
    {
        "name": "embedded",
        "baseName": "_embedded",
        "type": "Error403ForbiddenListEmbedded"
    }
];
