"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Error402PaymentRequiredEmbeddedErrorsInnerLinks = void 0;
class Error402PaymentRequiredEmbeddedErrorsInnerLinks {
    static getAttributeTypeMap() {
        return Error402PaymentRequiredEmbeddedErrorsInnerLinks.attributeTypeMap;
    }
}
exports.Error402PaymentRequiredEmbeddedErrorsInnerLinks = Error402PaymentRequiredEmbeddedErrorsInnerLinks;
Error402PaymentRequiredEmbeddedErrorsInnerLinks.discriminator = undefined;
Error402PaymentRequiredEmbeddedErrorsInnerLinks.attributeTypeMap = [
    {
        "name": "source",
        "baseName": "source",
        "type": "ApplicationLinksApplicationProfile"
    }
];
