/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export class ListSubscriptionSchedulesQueryParams {
    static getAttributeTypeMap() {
        return ListSubscriptionSchedulesQueryParams.attributeTypeMap;
    }
}
ListSubscriptionSchedulesQueryParams.discriminator = undefined;
ListSubscriptionSchedulesQueryParams.attributeTypeMap = [
    {
        "name": "nickname",
        "baseName": "nickname",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    }
];
//# sourceMappingURL=listSubscriptionSchedulesQueryParams.js.map