"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReserveProfilesListEmbedded = void 0;
class ReserveProfilesListEmbedded {
    'reserveProfiles';
    static discriminator = undefined;
    static attributeTypeMap = [
        {
            "name": "reserveProfiles",
            "baseName": "reserve_profiles",
            "type": "Set<ReserveProfile>"
        }
    ];
    static getAttributeTypeMap() {
        return ReserveProfilesListEmbedded.attributeTypeMap;
    }
}
exports.ReserveProfilesListEmbedded = ReserveProfilesListEmbedded;
//# sourceMappingURL=reserveProfilesListEmbedded.js.map