/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApplicationLinksApplicationProfile } from './applicationLinksApplicationProfile';

export class ReviewQueueItemsListEmbeddedReviewQueueItemsInnerLinks {
    'application'?: ApplicationLinksApplicationProfile;
    'identity'?: ApplicationLinksApplicationProfile;
    'merchant'?: ApplicationLinksApplicationProfile;
    'reviewBy'?: ApplicationLinksApplicationProfile;
    'self'?: ApplicationLinksApplicationProfile;
    'settlement'?: ApplicationLinksApplicationProfile;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "application",
            "baseName": "application",
            "type": "ApplicationLinksApplicationProfile"
        },
        {
            "name": "identity",
            "baseName": "identity",
            "type": "ApplicationLinksApplicationProfile"
        },
        {
            "name": "merchant",
            "baseName": "merchant",
            "type": "ApplicationLinksApplicationProfile"
        },
        {
            "name": "reviewBy",
            "baseName": "review_by",
            "type": "ApplicationLinksApplicationProfile"
        },
        {
            "name": "self",
            "baseName": "self",
            "type": "ApplicationLinksApplicationProfile"
        },
        {
            "name": "settlement",
            "baseName": "settlement",
            "type": "ApplicationLinksApplicationProfile"
        }    ];

    static getAttributeTypeMap() {
        return ReviewQueueItemsListEmbeddedReviewQueueItemsInnerLinks.attributeTypeMap;
    }
}

