"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Transfer = void 0;
/**
*
*/
class Transfer {
    static getAttributeTypeMap() {
        return Transfer.attributeTypeMap;
    }
}
exports.Transfer = Transfer;
Transfer.discriminator = undefined;
Transfer.attributeTypeMap = [
    {
        "name": "tags",
        "baseName": "tags",
        "type": "{ [key: string]: string; }"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "Transfer.TypeEnum"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "createdAt",
        "baseName": "created_at",
        "type": "Date"
    },
    {
        "name": "updatedAt",
        "baseName": "updated_at",
        "type": "Date"
    },
    {
        "name": "amount",
        "baseName": "amount",
        "type": "number"
    },
    {
        "name": "application",
        "baseName": "application",
        "type": "string"
    },
    {
        "name": "cardPresentDetails",
        "baseName": "card_present_details",
        "type": "CardPresentDetails"
    },
    {
        "name": "currency",
        "baseName": "currency",
        "type": "Currency"
    },
    {
        "name": "destination",
        "baseName": "destination",
        "type": "string"
    },
    {
        "name": "device",
        "baseName": "device",
        "type": "string"
    },
    {
        "name": "fee",
        "baseName": "fee",
        "type": "number"
    },
    {
        "name": "feeType",
        "baseName": "fee_type",
        "type": "FeeType"
    },
    {
        "name": "idempotencyId",
        "baseName": "idempotency_id",
        "type": "string"
    },
    {
        "name": "identity",
        "baseName": "identity",
        "type": "string"
    },
    {
        "name": "merchantIdentity",
        "baseName": "merchant_identity",
        "type": "string"
    },
    {
        "name": "messages",
        "baseName": "messages",
        "type": "Array<string>"
    },
    {
        "name": "raw",
        "baseName": "raw",
        "type": "object"
    },
    {
        "name": "readyToSettleAt",
        "baseName": "ready_to_settle_at",
        "type": "Date"
    },
    {
        "name": "source",
        "baseName": "source",
        "type": "string"
    },
    {
        "name": "state",
        "baseName": "state",
        "type": "Transfer.StateEnum"
    },
    {
        "name": "statementDescriptor",
        "baseName": "statement_descriptor",
        "type": "string"
    },
    {
        "name": "subtype",
        "baseName": "subtype",
        "type": "Transfer.SubtypeEnum"
    },
    {
        "name": "traceId",
        "baseName": "trace_id",
        "type": "string"
    },
    {
        "name": "externallyFunded",
        "baseName": "externally_funded",
        "type": "string"
    },
    {
        "name": "failureCode",
        "baseName": "failure_code",
        "type": "string"
    },
    {
        "name": "failureMessage",
        "baseName": "failure_message",
        "type": "string"
    },
    {
        "name": "links",
        "baseName": "_links",
        "type": "TransferLinks"
    }
];
(function (Transfer) {
    let TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["Debit"] = 'DEBIT'] = "Debit";
        TypeEnum[TypeEnum["Credit"] = 'CREDIT'] = "Credit";
        TypeEnum[TypeEnum["Reversal"] = 'REVERSAL'] = "Reversal";
        TypeEnum[TypeEnum["Fee"] = 'FEE'] = "Fee";
        TypeEnum[TypeEnum["Adjustment"] = 'ADJUSTMENT'] = "Adjustment";
        TypeEnum[TypeEnum["Dispute"] = 'DISPUTE'] = "Dispute";
        TypeEnum[TypeEnum["Reserve"] = 'RESERVE'] = "Reserve";
        TypeEnum[TypeEnum["Settlement"] = 'SETTLEMENT'] = "Settlement";
        TypeEnum[TypeEnum["Unknown"] = 'UNKNOWN'] = "Unknown";
    })(TypeEnum = Transfer.TypeEnum || (Transfer.TypeEnum = {}));
    let StateEnum;
    (function (StateEnum) {
        StateEnum[StateEnum["Canceled"] = 'CANCELED'] = "Canceled";
        StateEnum[StateEnum["Pending"] = 'PENDING'] = "Pending";
        StateEnum[StateEnum["Failed"] = 'FAILED'] = "Failed";
        StateEnum[StateEnum["Succeeded"] = 'SUCCEEDED'] = "Succeeded";
        StateEnum[StateEnum["Unknown"] = 'UNKNOWN'] = "Unknown";
    })(StateEnum = Transfer.StateEnum || (Transfer.StateEnum = {}));
    let SubtypeEnum;
    (function (SubtypeEnum) {
        SubtypeEnum[SubtypeEnum["Api"] = 'API'] = "Api";
        SubtypeEnum[SubtypeEnum["ApplicationFee"] = 'APPLICATION_FEE'] = "ApplicationFee";
        SubtypeEnum[SubtypeEnum["Dispute"] = 'DISPUTE'] = "Dispute";
        SubtypeEnum[SubtypeEnum["MerchantCredit"] = 'MERCHANT_CREDIT'] = "MerchantCredit";
        SubtypeEnum[SubtypeEnum["MerchantCreditAdjustment"] = 'MERCHANT_CREDIT_ADJUSTMENT'] = "MerchantCreditAdjustment";
        SubtypeEnum[SubtypeEnum["MerchantDebit"] = 'MERCHANT_DEBIT'] = "MerchantDebit";
        SubtypeEnum[SubtypeEnum["MerchantDebitAdjustment"] = 'MERCHANT_DEBIT_ADJUSTMENT'] = "MerchantDebitAdjustment";
        SubtypeEnum[SubtypeEnum["PlatformCredit"] = 'PLATFORM_CREDIT'] = "PlatformCredit";
        SubtypeEnum[SubtypeEnum["PlatformCreditAdjustment"] = 'PLATFORM_CREDIT_ADJUSTMENT'] = "PlatformCreditAdjustment";
        SubtypeEnum[SubtypeEnum["PlatformDebit"] = 'PLATFORM_DEBIT'] = "PlatformDebit";
        SubtypeEnum[SubtypeEnum["PlatformDebitAdjustment"] = 'PLATFORM_DEBIT_ADJUSTMENT'] = "PlatformDebitAdjustment";
        SubtypeEnum[SubtypeEnum["PlatformFee"] = 'PLATFORM_FEE'] = "PlatformFee";
        SubtypeEnum[SubtypeEnum["SettlementMerchant"] = 'SETTLEMENT_MERCHANT'] = "SettlementMerchant";
        SubtypeEnum[SubtypeEnum["SettlementNoop"] = 'SETTLEMENT_NOOP'] = "SettlementNoop";
        SubtypeEnum[SubtypeEnum["SettlementPartner"] = 'SETTLEMENT_PARTNER'] = "SettlementPartner";
        SubtypeEnum[SubtypeEnum["SettlementPlatform"] = 'SETTLEMENT_PLATFORM'] = "SettlementPlatform";
        SubtypeEnum[SubtypeEnum["SplitPayout"] = 'SPLIT_PAYOUT'] = "SplitPayout";
        SubtypeEnum[SubtypeEnum["SplitPayoutAdjustment"] = 'SPLIT_PAYOUT_ADJUSTMENT'] = "SplitPayoutAdjustment";
        SubtypeEnum[SubtypeEnum["System"] = 'SYSTEM'] = "System";
    })(SubtypeEnum = Transfer.SubtypeEnum || (Transfer.SubtypeEnum = {}));
})(Transfer = exports.Transfer || (exports.Transfer = {}));
