"use strict";
/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpdateUserRequest = void 0;
class UpdateUserRequest {
    static getAttributeTypeMap() {
        return UpdateUserRequest.attributeTypeMap;
    }
}
exports.UpdateUserRequest = UpdateUserRequest;
UpdateUserRequest.discriminator = undefined;
UpdateUserRequest.attributeTypeMap = [
    {
        "name": "tags",
        "baseName": "tags",
        "type": "{ [key: string]: string; }"
    },
    {
        "name": "enabled",
        "baseName": "enabled",
        "type": "boolean"
    }
];
//# sourceMappingURL=updateUserRequest.js.map