version: 2.1

jobs:
  assemble:
    docker:
      - image: cimg/node:18.4.0
    resource_class: medium

    steps:
      - checkout
      - run:
          name: build
          command: |
            npm install 
            npm install -g typescript
            tsc --build tsconfig.json 
      - run:
          name: test - typescript
          command: npm test -- -w=2
      - run: 
          name: test - javascript
          command: |
            ./node_modules/.bin/mocha src/test/filesTestJS.js
            ./node_modules/.bin/mocha src/test/transfersTestJS.js
      - run: 
          name: show src files 
          command: ls -Rlt src


  deploy:
    docker:
      - image: cimg/node:18.4.0
    resource_class: medium

    steps:
      - checkout
      - run:
          name: build
          command: |
            mkdir -p ~/.m2
            cp .m2/settings.xml ~/.m2 
            echo -e $GPG_KEY > PRIVATE_GPG_KEY.asc
            gpg --batch --import PRIVATE_GPG_KEY.asc
            mvn package
            mvn -Drepo.id=${ID} -Drepo.username=${NEXUS_USER} -Drepo.password=${NEXUS_PASSWORD} -Dgpg.keyname="${GPG_ID}" -Dgpg.passphrase="${GPG_PASSP}" verify gpg:sign install:install deploy:deploy
          working_directory: ~/project

workflows:
  version: 2

  assemble:
    jobs:
      - assemble

  build-deploy:
      jobs:
        - deploy:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v[0-9]+.*$/
