/**
 * Finix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-02-01
 * Contact: support@finixpayments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import localVarRequest from 'request';
import { ObjectSerializer, VoidAuth, SuperSet } from '../model/models';
import { HttpBasicAuth } from '../model/models';
import { HttpError } from './apis';
import { error } from 'console';
let defaultBasePath = 'https://finix.sandbox-payments-api.com';
// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================
export var SubscriptionAmountsApiApiKeys;
(function (SubscriptionAmountsApiApiKeys) {
})(SubscriptionAmountsApiApiKeys || (SubscriptionAmountsApiApiKeys = {}));
export class SubscriptionAmountsApi {
    constructor(basePathOrUsername, password, basePath) {
        this._basePath = defaultBasePath;
        this._defaultHeaders = {};
        this._useQuerystring = false;
        this.authentications = {
            'default': new VoidAuth(),
            'BasicAuth': new HttpBasicAuth(),
        };
        this.interceptors = [];
        if (password) {
            this.username = basePathOrUsername;
            this.password = password;
            if (basePath) {
                this.basePath = basePath;
            }
        }
        else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername;
            }
        }
    }
    set useQuerystring(value) {
        this._useQuerystring = value;
    }
    set basePath(basePath) {
        this._basePath = basePath;
    }
    set defaultHeaders(defaultHeaders) {
        this._defaultHeaders = defaultHeaders;
    }
    get defaultHeaders() {
        return this._defaultHeaders;
    }
    get basePath() {
        return this._basePath;
    }
    setDefaultAuthentication(auth) {
        this.authentications.default = auth;
    }
    setApiKey(key, value) {
        this.authentications[SubscriptionAmountsApiApiKeys[key]].apiKey = value;
    }
    set username(username) {
        this.authentications.BasicAuth.username = username;
    }
    set password(password) {
        this.authentications.BasicAuth.password = password;
    }
    addInterceptor(interceptor) {
        this.interceptors.push(interceptor);
    }
    /**
     * Helper function.
     * Create a `subscription_amount`.  The `Subscription Amount` is the amount to be charged to a `Merchant`. The `Subscription Amount` must be associated to a `Subscription Schedule`.
     * @summary Create a Subscription Amount
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     * @param createSubscriptionAmountRequest
     */
    lcreateHelper(subscriptionScheduleId, createSubscriptionAmountRequest, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const localVarPath = this.basePath + '/subscription/subscription_schedules/{subscription_schedule_id}/subscription_amounts'
                .replace('{' + 'subscription_schedule_id' + '}', encodeURIComponent(String(subscriptionScheduleId)));
            let localVarQueryParameters = {};
            let localVarHeaderParams = Object.assign({}, this._defaultHeaders);
            const produces = ['application/hal+json'];
            // give precedence to 'application/json'
            if (produces.indexOf('application/json') >= 0) {
                localVarHeaderParams.Accept = 'application/json';
            }
            else {
                localVarHeaderParams.Accept = produces.join(',');
            }
            let localVarFormParams = {};
            // verify required parameter 'subscriptionScheduleId' is not null or undefined
            if (subscriptionScheduleId === null || subscriptionScheduleId === undefined) {
                throw new Error('Required parameter subscriptionScheduleId was null or undefined when calling createSubscriptionAmounts.');
            }
            Object.assign(localVarHeaderParams, options.headers);
            localVarHeaderParams['Finix-Version'] = "2022-02-01";
            let localVarUseFormData = false;
            let localVarRequestOptions = {
                method: 'POST',
                qs: localVarQueryParameters,
                headers: localVarHeaderParams,
                uri: localVarPath,
                useQuerystring: this._useQuerystring,
                json: true,
            };
            if (createSubscriptionAmountRequest != undefined && createSubscriptionAmountRequest != null && createSubscriptionAmountRequest.hasOwnProperty('file')) {
                localVarRequestOptions.formData = createSubscriptionAmountRequest;
            }
            else {
                localVarRequestOptions.body = ObjectSerializer.serialize(createSubscriptionAmountRequest, "CreateSubscriptionAmountRequest");
            }
            let authenticationPromise = Promise.resolve();
            if (this.authentications.BasicAuth.username && this.authentications.BasicAuth.password) {
                authenticationPromise = authenticationPromise.then(() => this.authentications.BasicAuth.applyToRequest(localVarRequestOptions));
            }
            authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
            let interceptorPromise = authenticationPromise;
            for (const interceptor of this.interceptors) {
                interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
            }
            return interceptorPromise.then(() => {
                if (Object.keys(localVarFormParams).length) {
                    if (localVarUseFormData) {
                        localVarRequestOptions.formData = localVarFormParams;
                    }
                    else {
                        localVarRequestOptions.form = localVarFormParams;
                    }
                }
                return new Promise((resolve, reject) => {
                    localVarRequest(localVarRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        }
                        else {
                            if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                                body = ObjectSerializer.deserialize(body, "SubscriptionAmount");
                                resolve({ response: response, body: body });
                            }
                            else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                });
            });
        });
    }
    /**
     * Create a `subscription_amount`.  The `Subscription Amount` is the amount to be charged to a `Merchant`. The `Subscription Amount` must be associated to a `Subscription Schedule`.
     * @summary Create a Subscription Amount
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     * @param createSubscriptionAmountRequest
     */
    lcreate(subscriptionScheduleId, createSubscriptionAmountRequest, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.lcreateHelper(subscriptionScheduleId, createSubscriptionAmountRequest, options);
            return responseObject.body;
        });
    }
    /**
     * Create a `subscription_amount`.  The `Subscription Amount` is the amount to be charged to a `Merchant`. The `Subscription Amount` must be associated to a `Subscription Schedule`.
     * @summary Create a Subscription Amount
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     * @param createSubscriptionAmountRequest
     */
    lcreateHttp(subscriptionScheduleId, createSubscriptionAmountRequest, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.lcreateHelper(subscriptionScheduleId, createSubscriptionAmountRequest, options);
            return responseObject;
        });
    }
    /**
     * Helper function.
     * Delete a previously created `Subscription Amount`.
     * @summary Delete a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     */
    deleteSubscriptionAmountHelper(subscriptionAmountId, subscriptionScheduleId, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const localVarPath = this.basePath + '/subscription/subscription_schedules/{subscription_schedule_id}/subscription_amounts/{subscription_amount_id}'
                .replace('{' + 'subscription_amount_id' + '}', encodeURIComponent(String(subscriptionAmountId)))
                .replace('{' + 'subscription_schedule_id' + '}', encodeURIComponent(String(subscriptionScheduleId)));
            let localVarQueryParameters = {};
            let localVarHeaderParams = Object.assign({}, this._defaultHeaders);
            const produces = ['application/hal+json'];
            // give precedence to 'application/json'
            if (produces.indexOf('application/json') >= 0) {
                localVarHeaderParams.Accept = 'application/json';
            }
            else {
                localVarHeaderParams.Accept = produces.join(',');
            }
            let localVarFormParams = {};
            // verify required parameter 'subscriptionAmountId' is not null or undefined
            if (subscriptionAmountId === null || subscriptionAmountId === undefined) {
                throw new Error('Required parameter subscriptionAmountId was null or undefined when calling deleteSubscriptionAmount.');
            }
            // verify required parameter 'subscriptionScheduleId' is not null or undefined
            if (subscriptionScheduleId === null || subscriptionScheduleId === undefined) {
                throw new Error('Required parameter subscriptionScheduleId was null or undefined when calling deleteSubscriptionAmount.');
            }
            Object.assign(localVarHeaderParams, options.headers);
            localVarHeaderParams['Finix-Version'] = "2022-02-01";
            let localVarUseFormData = false;
            let localVarRequestOptions = {
                method: 'DELETE',
                qs: localVarQueryParameters,
                headers: localVarHeaderParams,
                uri: localVarPath,
                useQuerystring: this._useQuerystring,
                json: true,
            };
            let authenticationPromise = Promise.resolve();
            if (this.authentications.BasicAuth.username && this.authentications.BasicAuth.password) {
                authenticationPromise = authenticationPromise.then(() => this.authentications.BasicAuth.applyToRequest(localVarRequestOptions));
            }
            authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
            let interceptorPromise = authenticationPromise;
            for (const interceptor of this.interceptors) {
                interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
            }
            return interceptorPromise.then(() => {
                if (Object.keys(localVarFormParams).length) {
                    if (localVarUseFormData) {
                        localVarRequestOptions.formData = localVarFormParams;
                    }
                    else {
                        localVarRequestOptions.form = localVarFormParams;
                    }
                }
                return new Promise((resolve, reject) => {
                    localVarRequest(localVarRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        }
                        else {
                            if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                                resolve({ response: response, body: body });
                            }
                            else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                });
            });
        });
    }
    /**
     * Delete a previously created `Subscription Amount`.
     * @summary Delete a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     */
    deleteSubscriptionAmount(subscriptionAmountId, subscriptionScheduleId, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.deleteSubscriptionAmountHelper(subscriptionAmountId, subscriptionScheduleId, options);
            return responseObject.body;
        });
    }
    /**
     * Delete a previously created `Subscription Amount`.
     * @summary Delete a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     */
    deleteSubscriptionAmountHttp(subscriptionAmountId, subscriptionScheduleId, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.deleteSubscriptionAmountHelper(subscriptionAmountId, subscriptionScheduleId, options);
            return responseObject;
        });
    }
    /**
     * Helper function.
     * Retrieve the details of a `subscription_amount`.
     * @summary Get a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     */
    getHelper(subscriptionAmountId, subscriptionScheduleId, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const localVarPath = this.basePath + '/subscription/subscription_schedules/{subscription_schedule_id}/subscription_amounts/{subscription_amount_id}'
                .replace('{' + 'subscription_amount_id' + '}', encodeURIComponent(String(subscriptionAmountId)))
                .replace('{' + 'subscription_schedule_id' + '}', encodeURIComponent(String(subscriptionScheduleId)));
            let localVarQueryParameters = {};
            let localVarHeaderParams = Object.assign({}, this._defaultHeaders);
            const produces = ['application/hal+json'];
            // give precedence to 'application/json'
            if (produces.indexOf('application/json') >= 0) {
                localVarHeaderParams.Accept = 'application/json';
            }
            else {
                localVarHeaderParams.Accept = produces.join(',');
            }
            let localVarFormParams = {};
            // verify required parameter 'subscriptionAmountId' is not null or undefined
            if (subscriptionAmountId === null || subscriptionAmountId === undefined) {
                throw new Error('Required parameter subscriptionAmountId was null or undefined when calling getSubscriptionAmount.');
            }
            // verify required parameter 'subscriptionScheduleId' is not null or undefined
            if (subscriptionScheduleId === null || subscriptionScheduleId === undefined) {
                throw new Error('Required parameter subscriptionScheduleId was null or undefined when calling getSubscriptionAmount.');
            }
            Object.assign(localVarHeaderParams, options.headers);
            localVarHeaderParams['Finix-Version'] = "2022-02-01";
            let localVarUseFormData = false;
            let localVarRequestOptions = {
                method: 'GET',
                qs: localVarQueryParameters,
                headers: localVarHeaderParams,
                uri: localVarPath,
                useQuerystring: this._useQuerystring,
                json: true,
            };
            let authenticationPromise = Promise.resolve();
            if (this.authentications.BasicAuth.username && this.authentications.BasicAuth.password) {
                authenticationPromise = authenticationPromise.then(() => this.authentications.BasicAuth.applyToRequest(localVarRequestOptions));
            }
            authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
            let interceptorPromise = authenticationPromise;
            for (const interceptor of this.interceptors) {
                interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
            }
            return interceptorPromise.then(() => {
                if (Object.keys(localVarFormParams).length) {
                    if (localVarUseFormData) {
                        localVarRequestOptions.formData = localVarFormParams;
                    }
                    else {
                        localVarRequestOptions.form = localVarFormParams;
                    }
                }
                return new Promise((resolve, reject) => {
                    localVarRequest(localVarRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        }
                        else {
                            if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                                body = ObjectSerializer.deserialize(body, "SubscriptionAmount");
                                resolve({ response: response, body: body });
                            }
                            else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                });
            });
        });
    }
    /**
     * Retrieve the details of a `subscription_amount`.
     * @summary Get a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     */
    get(subscriptionAmountId, subscriptionScheduleId, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.getHelper(subscriptionAmountId, subscriptionScheduleId, options);
            return responseObject.body;
        });
    }
    /**
     * Retrieve the details of a `subscription_amount`.
     * @summary Get a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     */
    getHttp(subscriptionAmountId, subscriptionScheduleId, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.getHelper(subscriptionAmountId, subscriptionScheduleId, options);
            return responseObject;
        });
    }
    /**
     * Helper function.
     * Retrive a list of `Subscription Amounts`.
     * @summary List Subscription Amounts

    * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
    *
    */
    listBySubscriptionScheduleHelper(subscriptionScheduleId, listSubscriptionAmountQueryParams, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const localVarPath = this.basePath + '/subscription/subscription_schedules/{subscription_schedule_id}/subscription_amounts'
                .replace('{' + 'subscription_schedule_id' + '}', encodeURIComponent(String(subscriptionScheduleId)));
            let localVarQueryParameters = {};
            let localVarHeaderParams = Object.assign({}, this._defaultHeaders);
            const produces = ['application/hal+json'];
            // give precedence to 'application/json'
            if (produces.indexOf('application/json') >= 0) {
                localVarHeaderParams.Accept = 'application/json';
            }
            else {
                localVarHeaderParams.Accept = produces.join(',');
            }
            let localVarFormParams = {};
            // verify required parameter 'subscriptionScheduleId' is not null or undefined
            if (subscriptionScheduleId === null || subscriptionScheduleId === undefined) {
                throw new Error('Required parameter subscriptionScheduleId was null or undefined when calling listSubscriptionAmount.');
            }
            if (listSubscriptionAmountQueryParams != undefined) {
                if (listSubscriptionAmountQueryParams.limit !== undefined) {
                    localVarQueryParameters['limit'] = ObjectSerializer.serialize(listSubscriptionAmountQueryParams.limit, "number");
                }
                if (listSubscriptionAmountQueryParams.afterCursor !== undefined) {
                    localVarQueryParameters['after_cursor'] = ObjectSerializer.serialize(listSubscriptionAmountQueryParams.afterCursor, "string");
                }
                if (listSubscriptionAmountQueryParams.beforeCursor !== undefined) {
                    localVarQueryParameters['before_cursor'] = ObjectSerializer.serialize(listSubscriptionAmountQueryParams.beforeCursor, "string");
                }
            }
            Object.assign(localVarHeaderParams, options.headers);
            localVarHeaderParams['Finix-Version'] = "2022-02-01";
            let localVarUseFormData = false;
            let localVarRequestOptions = {
                method: 'GET',
                qs: localVarQueryParameters,
                headers: localVarHeaderParams,
                uri: localVarPath,
                useQuerystring: this._useQuerystring,
                json: true,
            };
            let authenticationPromise = Promise.resolve();
            if (this.authentications.BasicAuth.username && this.authentications.BasicAuth.password) {
                authenticationPromise = authenticationPromise.then(() => this.authentications.BasicAuth.applyToRequest(localVarRequestOptions));
            }
            authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
            let interceptorPromise = authenticationPromise;
            for (const interceptor of this.interceptors) {
                interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
            }
            return interceptorPromise.then(() => {
                if (Object.keys(localVarFormParams).length) {
                    if (localVarUseFormData) {
                        localVarRequestOptions.formData = localVarFormParams;
                    }
                    else {
                        localVarRequestOptions.form = localVarFormParams;
                    }
                }
                return new Promise((resolve, reject) => {
                    localVarRequest(localVarRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        }
                        else {
                            if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                                body = ObjectSerializer.deserialize(body, "SubscriptionAmountList");
                                resolve({ response: response, body: body });
                            }
                            else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                });
            });
        });
    }
    /**
     * Retrive a list of `Subscription Amounts`.
     * @summary List Subscription Amounts
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     *
     */
    listBySubscriptionSchedule(subscriptionScheduleId, listSubscriptionAmountQueryParams, options = { headers: {} }) {
        var _a, _b;
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.listBySubscriptionScheduleHelper(subscriptionScheduleId, listSubscriptionAmountQueryParams, options);
            // var queryParam: ListSubscriptionAmountQueryParams;
            var reachedEnd;
            if ((_b = (_a = responseObject.body) === null || _a === void 0 ? void 0 : _a.page) === null || _b === void 0 ? void 0 : _b.hasOwnProperty('nextCursor')) {
                var queryParam = {
                    afterCursor: '',
                    limit: 20
                };
                [queryParam, reachedEnd] = this.getCursorQueryParam(responseObject, queryParam);
            }
            else {
                var queryParam = {
                    offset: '',
                    limit: 20
                };
                [queryParam, reachedEnd] = this.getoffsetQueryParam(responseObject, queryParam);
            }
            const nextFetch = (limit) => {
                queryParam.limit = limit;
                if (reachedEnd) {
                    throw new error("End of list reached");
                }
                return this.listBySubscriptionSchedule(subscriptionScheduleId, queryParam);
            };
            let dataList = new SuperSet(nextFetch);
            dataList = yield this.embeddedHelper(responseObject, dataList);
            return dataList;
        });
    }
    /**
     * Retrive a list of `Subscription Amounts`.
     * @summary List Subscription Amounts
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     *
     */
    listBySubscriptionScheduleHttp(subscriptionScheduleId, listSubscriptionAmountQueryParams, options = { headers: {} }) {
        var _a, _b;
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.listBySubscriptionScheduleHelper(subscriptionScheduleId, listSubscriptionAmountQueryParams, options);
            //var queryParam: ListSubscriptionAmountQueryParams;
            var reachedEnd;
            if ((_b = (_a = responseObject.body) === null || _a === void 0 ? void 0 : _a.page) === null || _b === void 0 ? void 0 : _b.hasOwnProperty('nextCursor')) {
                var queryParam = {
                    afterCursor: '',
                    limit: 20
                };
                [queryParam, reachedEnd] = this.getCursorQueryParam(responseObject, queryParam);
            }
            else {
                var queryParam = {
                    offset: '',
                    limit: 20
                };
                [queryParam, reachedEnd] = this.getoffsetQueryParam(responseObject, queryParam);
            }
            const nextFetch = (limit) => {
                queryParam.limit = limit;
                if (reachedEnd) {
                    throw new error("End of list reached");
                }
                return this.listBySubscriptionSchedule(subscriptionScheduleId, queryParam);
            };
            let dataList = new SuperSet(nextFetch);
            dataList = yield this.embeddedHelper(responseObject, dataList);
            return Promise.resolve({ response: responseObject.response, body: dataList });
        });
    }
    /**
     * Helper function.
     * Update the details of a `subscription_amount`.
     * @summary Update a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     * @param createSubscriptionAmountRequest
     */
    patchSubscriptionAmountHelper(subscriptionAmountId, subscriptionScheduleId, createSubscriptionAmountRequest, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const localVarPath = this.basePath + '/subscription/subscription_schedules/{subscription_schedule_id}/subscription_amounts/{subscription_amount_id}'
                .replace('{' + 'subscription_amount_id' + '}', encodeURIComponent(String(subscriptionAmountId)))
                .replace('{' + 'subscription_schedule_id' + '}', encodeURIComponent(String(subscriptionScheduleId)));
            let localVarQueryParameters = {};
            let localVarHeaderParams = Object.assign({}, this._defaultHeaders);
            const produces = ['application/hal+json'];
            // give precedence to 'application/json'
            if (produces.indexOf('application/json') >= 0) {
                localVarHeaderParams.Accept = 'application/json';
            }
            else {
                localVarHeaderParams.Accept = produces.join(',');
            }
            let localVarFormParams = {};
            // verify required parameter 'subscriptionAmountId' is not null or undefined
            if (subscriptionAmountId === null || subscriptionAmountId === undefined) {
                throw new Error('Required parameter subscriptionAmountId was null or undefined when calling patchSubscriptionAmount.');
            }
            // verify required parameter 'subscriptionScheduleId' is not null or undefined
            if (subscriptionScheduleId === null || subscriptionScheduleId === undefined) {
                throw new Error('Required parameter subscriptionScheduleId was null or undefined when calling patchSubscriptionAmount.');
            }
            Object.assign(localVarHeaderParams, options.headers);
            localVarHeaderParams['Finix-Version'] = "2022-02-01";
            let localVarUseFormData = false;
            let localVarRequestOptions = {
                method: 'PATCH',
                qs: localVarQueryParameters,
                headers: localVarHeaderParams,
                uri: localVarPath,
                useQuerystring: this._useQuerystring,
                json: true,
            };
            if (createSubscriptionAmountRequest != undefined && createSubscriptionAmountRequest != null && createSubscriptionAmountRequest.hasOwnProperty('file')) {
                localVarRequestOptions.formData = createSubscriptionAmountRequest;
            }
            else {
                localVarRequestOptions.body = ObjectSerializer.serialize(createSubscriptionAmountRequest, "CreateSubscriptionAmountRequest");
            }
            let authenticationPromise = Promise.resolve();
            if (this.authentications.BasicAuth.username && this.authentications.BasicAuth.password) {
                authenticationPromise = authenticationPromise.then(() => this.authentications.BasicAuth.applyToRequest(localVarRequestOptions));
            }
            authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
            let interceptorPromise = authenticationPromise;
            for (const interceptor of this.interceptors) {
                interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
            }
            return interceptorPromise.then(() => {
                if (Object.keys(localVarFormParams).length) {
                    if (localVarUseFormData) {
                        localVarRequestOptions.formData = localVarFormParams;
                    }
                    else {
                        localVarRequestOptions.form = localVarFormParams;
                    }
                }
                return new Promise((resolve, reject) => {
                    localVarRequest(localVarRequestOptions, (error, response, body) => {
                        if (error) {
                            reject(error);
                        }
                        else {
                            if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                                body = ObjectSerializer.deserialize(body, "SubscriptionAmount");
                                resolve({ response: response, body: body });
                            }
                            else {
                                reject(new HttpError(response, body, response.statusCode));
                            }
                        }
                    });
                });
            });
        });
    }
    /**
     * Update the details of a `subscription_amount`.
     * @summary Update a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     * @param createSubscriptionAmountRequest
     */
    patchSubscriptionAmount(subscriptionAmountId, subscriptionScheduleId, createSubscriptionAmountRequest, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.patchSubscriptionAmountHelper(subscriptionAmountId, subscriptionScheduleId, createSubscriptionAmountRequest, options);
            return responseObject.body;
        });
    }
    /**
     * Update the details of a `subscription_amount`.
     * @summary Update a Subscription Amount
     * @param subscriptionAmountId The ID of the &#x60;Subscription Amount&#x60;.
     * @param subscriptionScheduleId The ID of the &#x60;Subscription Schedule&#x60;.
     * @param createSubscriptionAmountRequest
     */
    patchSubscriptionAmountHttp(subscriptionAmountId, subscriptionScheduleId, createSubscriptionAmountRequest, options = { headers: {} }) {
        return __awaiter(this, void 0, void 0, function* () {
            const responseObject = yield this.patchSubscriptionAmountHelper(subscriptionAmountId, subscriptionScheduleId, createSubscriptionAmountRequest, options);
            return responseObject;
        });
    }
    embeddedHelper(responseObject, dataList) {
        return __awaiter(this, void 0, void 0, function* () {
            if (responseObject.body.embedded == null || responseObject.body.embedded == undefined) {
                // const dataList = new SuperSet<any>();
                dataList.page = responseObject.body.page;
                dataList.links = responseObject.body.links;
                return dataList;
            }
            const embeddedName = Object.getOwnPropertyNames(responseObject.body.embedded)[0];
            let tempList = responseObject.body.embedded[embeddedName];
            // const dataList = new SuperSet<any>();
            tempList.forEach(item => { dataList.add(item); });
            dataList.page = responseObject.body.page;
            dataList.links = responseObject.body.links;
            return dataList;
        });
    }
    getoffsetQueryParam(responseObject, queryParam) {
        queryParam.offset = responseObject.body.page.offset;
        var endReached = false;
        if (responseObject.body.page.offset + responseObject.body.page.limit > responseObject.body.page.count) {
            endReached = true;
        }
        return [queryParam, endReached];
    }
    getCursorQueryParam(responseObject, queryParam) {
        queryParam.afterCursor = responseObject.body.page.nextCursor;
        var endReached = false;
        if (responseObject.body.page.nextCursor == undefined) {
            endReached = true;
        }
        return [queryParam, endReached];
    }
}
//# sourceMappingURL=subscriptionAmountsApi.js.map